# Generated by Django 4.2.25 on 2025-11-19 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Your full name', max_length=200)),
                ('tagline', models.CharField(help_text='Professional tagline/title', max_length=200)),
                ('bio', models.TextField(help_text='Short bio/about yourself')),
                ('profile_picture', models.ImageField(blank=True, help_text='Professional profile photo', null=True, upload_to='profile/')),
                ('resume', models.FileField(blank=True, help_text='Upload your resume (PDF)', null=True, upload_to='resumes/')),
                ('email', models.EmailField(blank=True, help_text='Professional email', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Contact phone', max_length=20)),
                ('location', models.CharField(blank=True, help_text='City, Country', max_length=200)),
                ('years_experience', models.PositiveIntegerField(default=0, help_text='Years of professional experience')),
                ('projects_completed', models.PositiveIntegerField(default=0, help_text='Total projects completed')),
                ('happy_clients', models.PositiveIntegerField(default=0, help_text='Number of satisfied clients')),
                ('meta_description', models.CharField(blank=True, help_text='Meta description for SEO', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Meta keywords, comma separated', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project title', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(help_text='Project description')),
                ('short_description', models.CharField(blank=True, help_text='Short description for listings', max_length=200)),
                ('thumbnail', models.ImageField(blank=True, help_text='Project thumbnail image', null=True, upload_to='projects/thumbnails/')),
                ('featured_image', models.ImageField(blank=True, help_text='Main project image', null=True, upload_to='projects/')),
                ('github_url', models.URLField(blank=True, help_text='GitHub repository URL', validators=[django.core.validators.URLValidator()])),
                ('live_url', models.URLField(blank=True, help_text='Live project URL', validators=[django.core.validators.URLValidator()])),
                ('demo_url', models.URLField(blank=True, help_text='Demo/Video URL', validators=[django.core.validators.URLValidator()])),
                ('technologies', models.CharField(help_text='Technologies used (comma separated)', max_length=500)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing'), ('planned', 'Planned')], default='completed', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('github_repo_name', models.CharField(blank=True, help_text='GitHub repository name (for auto-sync)', max_length=200)),
                ('github_stars', models.PositiveIntegerField(default=0, editable=False)),
                ('github_forks', models.PositiveIntegerField(default=0, editable=False)),
                ('github_language', models.CharField(blank=True, editable=False, max_length=50)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('medium', 'Medium'), ('stackoverflow', 'Stack Overflow'), ('other', 'Other')], max_length=50)),
                ('url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('icon_class', models.CharField(blank=True, help_text='FontAwesome icon class (e.g., fab fa-github)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['order', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Person's name", max_length=200)),
                ('position', models.CharField(help_text='Job title/position', max_length=200)),
                ('company', models.CharField(blank=True, help_text='Company name', max_length=200)),
                ('testimonial', models.TextField(help_text='Testimonial text')),
                ('avatar', models.ImageField(blank=True, help_text="Person's photo", null=True, upload_to='testimonials/')),
                ('rating', models.PositiveIntegerField(default=5, help_text='Rating out of 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
