# Generated by Django 4.2.25 on 2025-11-19 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Service title', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('short_description', models.CharField(help_text='Brief description for cards', max_length=200)),
                ('description', models.TextField(help_text='Detailed service description')),
                ('icon_class', models.CharField(default='fas fa-code', help_text='FontAwesome icon class (e.g., fas fa-code)', max_length=100)),
                ('color', models.CharField(default='primary', help_text='Bootstrap color class', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Service image/illustration', null=True, upload_to='services/')),
                ('price_starting', models.DecimalField(blank=True, decimal_places=2, help_text='Starting price (optional)', max_digits=10, null=True)),
                ('price_currency', models.CharField(default='USD', help_text='Currency code (USD, EUR, etc.)', max_length=3)),
                ('pricing_model', models.CharField(blank=True, help_text="e.g., 'per hour', 'per project', 'monthly'", max_length=100)),
                ('features', models.TextField(blank=True, help_text='Service features/highlights (one per line or comma-separated)')),
                ('delivery_time', models.CharField(blank=True, help_text="Typical delivery time (e.g., '2-3 weeks')", max_length=100)),
                ('is_featured', models.BooleanField(default=False, help_text='Show prominently on homepage')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('budget', models.CharField(blank=True, max_length=100)),
                ('timeline', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='services.service')),
            ],
            options={
                'verbose_name': 'Service Inquiry',
                'verbose_name_plural': 'Service Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
