# Generated by Django 4.2.25 on 2025-11-19 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Certification name', max_length=200)),
                ('issuing_organization', models.CharField(help_text='Issuing organization', max_length=200)),
                ('credential_id', models.CharField(blank=True, help_text='Credential ID/License number', max_length=200)),
                ('credential_url', models.URLField(blank=True, help_text='Verification URL', validators=[django.core.validators.URLValidator()])),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, help_text='Leave blank if no expiration', null=True)),
                ('description', models.TextField(blank=True, help_text='Description and skills gained')),
                ('logo', models.ImageField(blank=True, help_text='Certification badge/logo', null=True, upload_to='certifications/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['order', '-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(help_text='School/University name', max_length=200)),
                ('degree', models.CharField(choices=[('phd', 'Ph.D.'), ('masters', "Master's Degree"), ('bachelors', "Bachelor's Degree"), ('associate', 'Associate Degree'), ('diploma', 'Diploma'), ('certificate', 'Certificate'), ('bootcamp', 'Bootcamp'), ('other', 'Other')], help_text='Degree type', max_length=20)),
                ('field_of_study', models.CharField(help_text='Major/Field of study', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description, achievements, relevant coursework')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if current', null=True)),
                ('is_current', models.BooleanField(default=False, help_text='Currently studying')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, help_text='Grade Point Average', max_digits=3, null=True)),
                ('location', models.CharField(blank=True, help_text='City, Country', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Institution logo', null=True, upload_to='education/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Skill name', max_length=100)),
                ('category', models.CharField(choices=[('frontend', 'Frontend Development'), ('backend', 'Backend Development'), ('database', 'Database'), ('devops', 'DevOps & Tools'), ('design', 'Design'), ('soft', 'Soft Skills'), ('other', 'Other')], default='other', max_length=20)),
                ('proficiency', models.PositiveIntegerField(help_text='Proficiency percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('icon_class', models.CharField(blank=True, help_text='FontAwesome or Devicon class (e.g., fab fa-python)', max_length=100)),
                ('color', models.CharField(default='success', help_text='Bootstrap color class (primary, success, info, warning, danger)', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Brief description of your experience with this skill')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['order', 'category', '-proficiency'],
            },
        ),
    ]
